_BASE_: "Base-DiffusionDet.yaml"
MODEL:
  WEIGHTS: "models/swin_base_patch4_window7_224_22k.pkl"
  BACKBONE:
    NAME: build_swintransformer_fpn_backbone
  SWIN:
    SIZE: B-22k
  FPN:
    IN_FEATURES: [ "swin0", "swin1", "swin2", "swin3" ]
  ROI_HEADS:
    NUM_CLASSES: 1  # crowdhuman
  DiffusionDet:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 1  # crowdhuman
    PRIOR_METHOD: "none"
DATASETS:  # crowdhuman
  TRAIN: ("CrowdHuman_train",)
  TEST: ("CrowdHuman_val",)
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.001
SOLVER:
  STEPS: (350000, 420000)
  MAX_ITER: 450000
  IMS_PER_BATCH: 1
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
TEST:  # crowdhuman
  EVAL_PERIOD: 5000  # disable eval during train since long time
